### ISSUE TITLE
Beautiful README / documentation

### ISSUE THREAD

**Issue by williamboxhall** [fwbrasil/clump#30]
I planning to do this eventually...

it should explain the purpose of the library then give a bunch of syntax examples

**Comment by williamboxhall** [comment]
@fwbrasil I want to start working on this soon. It would be both the README as well as scaladoc in Clump.scala and ClumpSource.scala.

For the README I would like to put a few examples, but how in-depth should it go? In the end, we can link people to the IntegrationSpec.scala for more examples.

In the examples I'd like to cover:
1) basic case with a for comprehensions, like [this](https://github.com/fwbrasil/clump/blob/master/src/test/scala/clump/IntegrationSpec.scala#L39)
2) one case showing the default filtering when something isn't materialized
3) maybe one case showing different filtering with .optional and .orElse ? 

For the pre text I guess I would talk about
1) What it is (service aggregation in particular abstracting on top of bulk fetching, batching and retries)
2) That it is a monad that can be used in for-comprehensions
3) That it has been heavily inspired by Twitter's Stitch

anything obvious that I've missed

**Comment by williamboxhall** [comment]
I guess I should talk about the different ways to create a ClumpSource too

**Comment by williamboxhall** [comment]
an example of traverse with a for comprehension and just a simple for-comprehension (one using clump.list and one using clump.get)

**Comment by fwbrasil** [comment]
Cool, we really need a nice readme. I would like to see some initial text more general about what is Clump followed by the usage documentation based on code samples with less text as possible.

**Comment by fwbrasil** [comment]
I'm also planning to write a separate doc comparing Clump and Stitch.

**Comment by fwbrasil** [comment]
fixed by https://github.com/fwbrasil/clump/pull/42
